trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'windows-latest' 

steps:
- task: UseNode@1
  inputs:
    versionSpec: '16.x'  
  displayName: 'Set up Node.js'

- checkout: self  
  displayName: 'Checkout Repository'

- script: |
    node -v  
  displayName: 'Check Node.js Version'

- script: |
    npm install  
  displayName: 'Install dependencies'

- script: |
    npm install -g typescript@4.4
    npm link typescript
    npm install playwright  
    npx playwright install  
  displayName: 'Install Playwright browsers'

- script: |
    npx tsc  
  displayName: 'Compile TypeScript'

- script: |
    npx ts-node playwright_test.ts tests/test1.json tests/test2.json --headless
  displayName: 'Run Playwright Tests'