trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '18.x'  
  displayName: 'Set up Node.js'

- checkout: self
  displayName: 'Checkout Repository'

- script: |
    node -v
    npm -v
  displayName: 'Check Node.js and npm Versions'

- script: |
    npm ci  # Use npm ci for more reliable dependency installation
  displayName: 'Install dependencies'

- script: |
    npm install -D typescript@latest
    npm install -D playwright@latest
    npm install -D @types/node@latest
    npx playwright install-deps
    npx playwright install
  displayName: 'Install Playwright and TypeScript'

- script: |
    npx tsc --noEmit
  displayName: 'Validate TypeScript'

- script: |
    npx playwright playwright_test.ts tests/test1.json tests/test2.json --headless
  displayName: 'Run Playwright Tests'
  continueOnError: true  

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Playwright Test Results'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'screenshots'
    ArtifactName: 'test-screenshots'
  condition: succeededOrFailed()