trigger:
  branches:
    include:
      - main =

pool:
  vmImage: 'windows-latest' 

steps:
- task: UseNode@1
  inputs:
    versionSpec: '16.x' 
  displayName: 'Set up Node.js'

- checkout: self 
  displayName: 'Checkout Repository'

- script: |
    npm install  
  displayName: 'Install dependencies'

- script: |
    npx playwright install 
  displayName: 'Install Playwright browsers'

- script: |
    npx tsc  
    node playwright_test.js tests/test1.json tests/test2.json --headless 
  displayName: 'Compile and run TypeScript tests'