trigger:
  branches:
    include:
      - main  # Adjust to your branch name

pool:
  vmImage: 'windows-latest'  # Use Windows-based agent

steps:
- task: UseNode@1
  inputs:
    versionSpec: '16.x'  # Set the Node.js version (adjust as needed)
  displayName: 'Set up Node.js'

- checkout: self  # Ensure the repository is checked out
  displayName: 'Checkout Repository'

- script: |
    node -v  # Check Node.js version
  displayName: 'Check Node.js Version'

- script: |
    npm install  # Install dependencies from package.json
  displayName: 'Install dependencies'

- script: |
    npm install playwright  # Explicitly install Playwright
    npx playwright install  # Install Playwright browser dependencies
  displayName: 'Install Playwright browsers'

- script: |
    npx tsc  # Compile TypeScript to JavaScript
    node playwright_test.js tests/test1.json tests/test2.json --headless  # Run the compiled TypeScript file
  displayName: 'Compile and run TypeScript tests'