trigger:
  branches:
    include:
      - main  # Adjust to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate VM image

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

- checkout: self  # Ensure the repository is checked out
  displayName: 'Checkout Repository'

- script: |
    python -m pip install --upgrade pip  # Ensure pip is up-to-date
    pip install -r requirements.txt  # Install dependencies from requirements.txt
  displayName: 'Install dependencies'

- script: |
    npx playwright install  # Install Playwright browser dependencies
  displayName: 'Install Playwright browsers'

- script: |
    python my_script.py tests/test1.json tests/test2.json  # Run your Python script with JSON files
  displayName: 'Run Python script with JSON files'