trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'windows-latest' 

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' 
  displayName: 'Set up Python'

- checkout: self 
  displayName: 'Checkout Repository'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt 
  displayName: 'Install dependencies'

- script: |
    npx playwright install
  displayName: 'Install Playwright browsers'

- script: |
    python playwright_demo.py tests/test1.json tests/test2.json 
  displayName: 'Run Python script with JSON files'