trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  testFiles: "tests/test1.json,tests/test2.json"  # Add your test files here
  headless: "true"  # Set to 'true' for headless mode, 'false' for non-headless

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '18.x'  
  displayName: 'Set up Node.js'

- checkout: self
  displayName: 'Checkout Repository'

- script: |
    node -v
    npm -v
  displayName: 'Check Node.js and npm Versions'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm install -D typescript@latest
    npm install -D playwright@latest
    npm install -D @types/node@latest
    npx playwright install-deps
    npx playwright install
  displayName: 'Install Playwright and TypeScript'

- script: |
    npx tsc --noEmit
  displayName: 'Validate TypeScript'

- script: |
    echo "Running tests..."
    node dist/playwright_test.js $(testFiles) --headless=$(headless)
  displayName: 'Run Playwright Tests'
  continueOnError: true  

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'test-results.json'
    ArtifactName: 'test-results-json'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'screenshots'
    ArtifactName: 'test-screenshots'
  condition: succeededOrFailed()