trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '16.x'
  displayName: 'Set up Node.js'

- checkout: self
  displayName: 'Checkout Repository'

- script: |
    node -v
  displayName: 'Check Node.js Version'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm install playwright
    npx playwright install
  displayName: 'Install Playwright browsers'

- script: |
    npx tsc
    node playwright_test.js tests/test1.json tests/test2.json --headless
  displayName: 'Compile and run TypeScript tests'
  shell: pwsh